### ISSUE TITLE
Is there support for enabling a SSL connection to Postgres?

### ISSUE THREAD

**Issue by kylehayes** [nearform/trail#255]
I can't find documentation for enabling an SSL connection to Postgres (which our database server requires). Looking at the code it doesn't look like the `ssl` attribute is being used when instantiating a new pg `Client`.

**Comment by simoneb** [comment]
It indeed isn't. Although, from the [pg docs](https://node-postgres.com/features/connecting):

> node-postgres uses the same environment variables as libpq to connect to a PostgreSQL server

And in the [libpq docs](https://www.postgresql.org/docs/9.5/libpq-envars.html) you will find all the environment variables it supports. I have not tried it, but I suspect you may be able to configure options which are not supported by this package via env vars.

**Comment by kylehayes** [comment]
Well that worked beautifully—thank you, @simoneb!
