### ISSUE TITLE
complex signatures

### ISSUE THREAD

**Issue by mcollina** [nearform/trail#3]
```
async insert (trailOrWhen, who, what, subject, where = {}, why = {}, meta = {}) {
```

looks very complex. Passing an object in `async insert(trail)` is more readable and flexible. The input should be validated anyway.

Also, I would discourage to use a `new Trail()` object

**Comment by mavdi** [comment]
Agreed. Passing in an object literal is way more readable. Will discuss this with @ShogunPanda

**Comment by ShogunPanda** [comment]
Ok, I'll change the code to use plain JS object and just leave validation functions.
