### ISSUE TITLE
Standalone Fastify options does not include CORS settings  

### ISSUE THREAD

**Issue by vjaitly** [nearform/trail#58]
I ma building a separate UI for the /trails API. However, the requests are failing due to CORS issue. The standalone fastify server does not include the CORS plugin (fastify-cors). Probably a config option to enable/disable the CORS plugin will be a good idea.

**Comment by vjaitly** [comment]
I could do a PR for this. Perhaps having just an env option to enable/disable would be enough ? Any one wanting to have more fine-grained control could spin off their own fastify and use the plugin option ?
@simoneb let me know how you would like the implementation to be.

**Comment by simoneb** [comment]
Yes that's a fair approach, we also do it this way. If you use an environment variable or a configuration of some sort, you could provide that as the `origin` option of the fastify-cors plugin.

**Comment by vjaitly** [comment]
@simoneb created a PR #59
